######################## default configuration ####################
# 网站的根URL (必需). 所有相对链接都会基于此地址.
# !!! 重要: 绑定自定义域名后，必须将这里修改为 "https://www.categoryoftea.org/"
baseURL = "https://categoryoftea.org/"

# 网站标题 (必需). 这是SEO的核心.
title = "Category of Tea | Your Ultimate Guide to Chinese Tea Varieties"

# 主题名称
theme = "hugoplate"

# 默认时区; 建议设置为对你最方便或对目标受众最合适的时区. "UTC" 是一个安全的中性选择.
# 更多时区: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timeZone = "UTC"

# 文章摘要长度 (按词数)
summaryLength = 70 # 原值为10太短了，70个词大概能显示2-3行，对摘要更友好.

# 默认语言设置
defaultContentLanguage = "en" # 确保是 'en'
# 在URL中不显示语言代码 (e.g. /about/ 而不是 /en/about/)
defaultContentLanguageInSubdir = false
# CJK语言支持, 英文网站设为false
hasCJKLanguage = false


########################### Services #############################
[services]
[services.googleAnalytics]
# TODO: 将 'G-MEASUREMENT_ID' 替换为你自己的Google Analytics ID. 如果暂时不用,可以留空或注释掉.
ID = 'G-MEASUREMENT_ID'

[services.disqus]
# TODO: 替换为自己的Disqus shortname. 如果不用评论功能, 直接留空即可.
shortname = "" # 原来的 "themefisher-template" 已清空


########################## Pagination ############################
[pagination]
# 博客列表页每页显示的文章数
pagerSize = 10


# =================================================================
# 以下部分是模板的高级技术配置，通常无需修改.
# 我已审查并确认它们适用于你的网站, 保持默认即可.
# =================================================================

########################## Permalinks ############################
[permalinks.page]
"pages" = "/:slugorcontentbasename/"

############################# Build ##############################
[build]
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/notwatching/hugo_stats\.json'
target = 'css'

############################# Modules ############################
[module]
[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
disableWatch = true
source = 'hugo_stats.json'
target = 'assets/notwatching/hugo_stats.json'

############################# Outputs ############################
[outputs]
home = ["HTML", "RSS", "WebAppManifest", "SearchIndex"] # 为搜索功能保留SearchIndex

############################# Imaging ############################
[imaging]
quality = 80
resampleFilter = "Lanczos"

############################ Caches ##############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"
[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

############################ Markup ##############################
[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'monokai'
lineNumbersInTable = false

[markup.tableOfContents]
startLevel = 2
endLevel = 5
ordered = true

########################### Media types ###########################
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

########################### Output Format ##########################
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true

############################# Plugins ##############################
# 这部分是模板自带的CSS和JS插件加载列表，无需修改.
# CSS Plugins
[[params.plugins.css]]
link = "plugins/swiper/swiper-bundle.css"
lazy = true
[[params.plugins.css]]
link = "plugins/glightbox/glightbox.css"
lazy = true
[[params.plugins.css]]
link = "plugins/font-awesome/v6/brands.css"
lazy = true
[[params.plugins.css]]
link = "plugins/font-awesome/v6/solid.css"
lazy = true
[[params.plugins.css]]
link = "plugins/font-awesome/v6/icons.css"
lazy = true

# JS Plugins
[[params.plugins.js]]
link = "js/search.js"
lazy = false
[[params.plugins.js]]
link = "plugins/swiper/swiper-bundle.js"
lazy = false
[[params.plugins.js]]
link = "plugins/cookie.js"
lazy = false
[[params.plugins.js]]
link = "plugins/glightbox/glightbox.js"
lazy = true
[[params.plugins.js]]
link = "js/gallery-slider.js"
lazy = true
[[params.plugins.js]]
link = "js/accordion.js"
lazy = true
[[params.plugins.js]]
link = "js/tab.js"
lazy = true
[[params.plugins.js]]
link = "js/modal.js"
lazy = true
[[params.plugins.js]]
link = "plugins/youtube-lite.js"
lazy = true
